module.exports = {
  arrowParens: "always",
  bracketSpacing: false,
  embeddedLanguageFormatting: "off",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  printWidth: 180,
  proseWrap: "always",
  quoteProps: "as-needed",
  rangeStart: 0,
  rangeEnd: Infinity,
  requirePragma: false,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  useTabs: false
}
